// English interface text. Keys are grouped by screen.
export default {
  app: {
    name: "Lakshyam",
    tagline: "for Kerala PSC preparation",
    loading: "Opening your study space…",
    dbError: "This browser couldn’t open the app’s storage. Open Lakshyam in Chrome (not in private mode) and try again."
  },
  common: {
    back: "Back",
    cancel: "Cancel",
    close: "Close",
    done: "Done",
    showMore: "Show {n} more",
    questions: (v) => (v.n === 1 ? "{n} question" : "{n} questions"),
    topics: (v) => (v.n === 1 ? "{n} topic" : "{n} topics"),
    papers: (v) => (v.n === 1 ? "{n} paper" : "{n} papers"),
    tests: (v) => (v.n === 1 ? "{n} test" : "{n} tests"),
    searchPlaceholder: "Search",
    save: "Save",
    add: "Add",
    create: "Create",
    delete: "Delete",
    edit: "Edit",
    ok: "OK",
    undo: "Undo",
    more: "More",
    copied: "Copied",
    copyFailed: "Couldn’t copy. Long-press the text to copy it by hand."
  },
  tabs: {
    today: "Today",
    library: "Library",
    progress: "Progress",
    notes: "Notes"
  },
  top: {
    noSyllabus: "No syllabus yet",
    search: "Search",
    settings: "Settings"
  },
  greeting: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening"
  },
  today: {
    goalLabel: "Today’s goal",
    goalProgress: "{done} of {goal} questions",
    welcomeTitle: "Bring your study data over",
    welcomeBody: "Pick the backup file you exported from PSC Exam Vault. You’ll see exactly what comes in before anything is saved. Your old app stays as it is.",
    importButton: "Import from PSC Exam Vault",
    readyTitle: "Your data is here",
    readyBody: "{papers} and {questions} in {syllabus}. Daily plans and progress insights arrive in the next updates.",
    openLibrary: "Open Library",
    offlineReady: "Works offline on this phone",
    continue: "Continue: {label}",
    startTest: "Start a test",
    greetName: "{greeting}, {name}",
    goalMet: "Goal reached today. Well done!",
    changeGoal: "Change goal",
    backupAgo: (v) => (v.n === 1 ? "Last backup 1 day ago" : "Last backup {n} days ago"),
    backupNever: "No backup of Lakshyam yet"
  },
  habits: {
    days: (v) => (v.n === 1 ? "1 day" : "{n} days"),
    streakLabel: "Study streak: {n} days in a row",
    weekLabel: "Studied on {n} days this week",
    dow: { 0: "M", 1: "T", 2: "W", 3: "T", 4: "F", 5: "S", 6: "S" },
    doneToday: "Studied today. See you tomorrow!",
    keepGoing: "Study a little today to keep it going.",
    getBack: "Get back today: one Quick 10 is enough.",
    start: "Take a test or mark a topic studied to start a streak."
  },
  next: {
    kicker: { due: "Due for review", weak: "Worth practising", new: "Not tried yet" },
    dueDays: (v) => (v.n === 1 ? "due 1 day ago" : "due {n} days ago"),
    dueToday: "due today",
    weak: "{pct}% right in {n} answers",
    new: "You haven’t answered these yet",
    quick: "Quick 10",
    open: "Open topic",
    another: "Another suggestion",
    dueTitle: (v) => (v.n === 1 ? "Due for review (1)" : "Due for review ({n})"),
    dueHint: "Topics you marked studied come back after 1, 2, 4, 7, 14, 30 and 60 days."
  },
  syllabus: {
    title: "Syllabus",
    hint: "Papers, topics and progress show for the syllabus you pick."
  },
  library: {
    views: { subjects: "Subjects", topics: "Topics", papers: "Papers", banks: "Banks" },
    emptyView: {
      subjects: "No subjects in this syllabus yet.",
      topics: "No topics here yet.",
      papers: "No papers in this syllabus yet. Tap “+ Add paper”.",
      banks: "No banks yet."
    },
    notStudied: "not studied yet",
    emptyTitle: "Your papers and questions will live here",
    emptyBody: "Import your backup from PSC Exam Vault to see subjects, topics and papers.",
    nothingFound: "Nothing matches “{q}”.",
    studied: "Studied {n}×",
    inSubject: "{subject}",
    noQuestions: "No questions here yet."
  },
  question: {
    number: "Q{n}",
    question: "Question",
    inTest: "Q{n}",
    paperNumber: "paper Q{n}",
    correct: "correct answer",
    yourPick: "your choice",
    showAnswer: "Show answer",
    more: "More actions",
    flag: "Flag",
    unflag: "Remove flag",
    flaggedToast: "Flagged · it’s in ⭐ Flagged",
    unflaggedToast: "Flag removed",
    setDifficulty: "Difficulty",
    clearDifficulty: "No difficulty",
    setAnswer: "Change correct answer",
    noAnswerOption: "No answer yet",
    edit: "Edit question",
    option: "Option {l}",
    addOption: "+ Add option",
    removeOption: "Remove last option",
    formatHint: "**word** highlights, *word* is italic, $x^2$ is maths.",
    formIncomplete: "Fill in the question and every option.",
    move: "Change subject / topic",
    movedTo: "Moved to {topic}",
    markDeleted: "Mark as deleted by PSC",
    undeletePsc: "Not deleted by PSC",
    addToBank: "Add to a bank",
    removeFromBank: "Remove from “{bank}”",
    removedFromBank: "Removed from the bank",
    copy: "Copy",
    delete: "Delete question",
    deleteTitle: "Delete this question?",
    deleteBody: "It is removed from its paper and from Library. You can undo right after.",
    deleteButton: "Delete",
    deletedToast: "Question deleted",
    editHint: "Tap an option to make it the correct answer. Tap it again to clear.",
    preview: "Question",
    deleted: "Deleted by PSC in the official answer key",
    noAnswer: "No correct answer marked yet",
    explanation: "Explanation",
    flagged: "Flagged",
    difficulty: { E: "Easy", M: "Medium", D: "Hard" }
  },
  view: {
    title: "How to show answers",
    study: "Study view",
    studyHint: "Correct answers shown",
    selftest: "Self-test view",
    selftestHint: "Answers hidden until you pick an option",
    edit: "Edit answers",
    editHint: "Tap an option to set the correct answer",
    editBanner: "Editing answers: tap an option to set it as correct."
  },
  sort: {
    title: "Order",
    none: "Paper order",
    "diff-asc": "Easy → Hard",
    "diff-desc": "Hard → Easy"
  },
  exams: {
    title: "Choose exams to include",
    hint: "Only changes this list. Untick an exam to leave out its questions.",
    all: "Exams: all {n}",
    some: "Exams: {n} of {of}",
    showing: "Showing {n} of {of} questions",
    search: "Search exams by name or post",
    selectAll: "Tick all shown",
    selectNone: "Untick all shown",
    templates: "Saved selections",
    noTemplates: "None saved for this syllabus yet.",
    templateName: "Save this selection as… (e.g. Last 3 exams)",
    useTemplate: "Use",
    applied: "Using “{name}”",
    saved: "Selection saved",
    pickOne: "Tick at least one exam",
    apply: "Apply"
  },
  listing: {
    copy: "Copy all questions"
  },
  studied: {
    button: "📖 Studied +1",
    done: "Marked as studied ({n}×)",
    minus: "Studied −1 (now {n}×)"
  },
  topics: {
    all: "All",
    sortFilter: "Sort & filter",
    sortBy: "Sort by",
    sort: { freq: "Most questions", az: "A–Z", most: "Most studied", least: "Least studied", label: "Label" },
    studiedFilter: "Studied",
    studied: { all: "All", "0": "Not studied", "1": "Studied", "3": "3+ times" },
    labelHint: "Tap colours to show only those. Tap again to drop one.",
    reset: "Reset",
    tip: "Tip: press and hold a topic to add it to a list or give it a label."
  },
  labels: {
    title: "Colour label",
    none: "No label",
    Red: "Red", Gold: "Gold", Green: "Green", Blue: "Blue", Purple: "Purple", Teal: "Teal"
  },
  lists: {
    newList: "New topic list",
    newShort: "+ List",
    namePlaceholder: "List name, e.g. Revision 1",
    addTitle: "Add to topic lists",
    none: "No topic lists yet.",
    menu: "List",
    addTopics: "Add or remove topics",
    rename: "Rename list",
    delete: "Delete list",
    deleteTitle: "Delete the list “{name}”?",
    deleteBody: "Only the list goes. Topics and questions stay.",
    deleted: "List deleted"
  },
  topicMenu: {
    open: "Open topic",
    addToList: "Add to a topic list",
    addLabel: "Add a colour label",
    changeLabel: "Colour label ({label})",
    removeFromList: "Remove from “{list}”",
    removed: "Removed from the list",
    rename: "Rename topic",
    renameHint: "If another one already has this name, the two are merged and nothing is lost.",
    renamed: "Renamed"
  },
  subjectMenu: {
    rename: "Rename subject"
  },
  subject: {
    allQuestions: "All questions"
  },
  merge: {
    title: "Merge into “{name}”?",
    topicBody: "“{from}” will be joined with “{to}”. Its questions, studied counts, labels, list entries, notes and test history move across. A safety copy is kept (Settings → Undo).",
    subjectBody: "“{from}” will be joined with “{to}”. Topics with the same name are merged; all questions, studied counts, labels, notes and test history move across. A safety copy is kept (Settings → Undo).",
    button: "Merge",
    done: "Merged into {name}"
  },
  picker: {
    pickSubject: "Pick a subject",
    pickTopic: "Pick a topic",
    subjects: "Subjects",
    newSubject: "+ New subject",
    newTopic: "+ New topic",
    subjectName: "Subject name",
    topicName: "Topic name"
  },
  paperMenu: {
    answerKey: "Add answer key",
    explanations: "Add explanations",
    rename: "Rename paper",
    postName: "Post name",
    move: "Move to another syllabus",
    moved: "Moved to {syllabus}",
    delete: "Delete paper",
    deleteTitle: "Delete “{name}”?",
    deleteBody: "The paper and its {n} questions are removed. Your test history keeps its scores. You can undo right after, and a safety copy is kept.",
    deleted: "Paper deleted"
  },
  addPaper: {
    button: "+ Add paper",
    title: "Add a question paper",
    hint: "Choose the paper’s JSON file, or paste the JSON an AI gave you. It goes into {syllabus}.",
    bankTitle: "Import questions into {bank}",
    bankHint: "Same JSON format as a question paper. The questions go into this bank only, not under Papers.",
    chooseFile: "Choose file",
    or: "or paste it here",
    pastePlaceholder: "{ \"paper\": { … }, \"questions\": [ … ] }",
    pasted: "Pasted text",
    check: "Check",
    cantUse: "Can’t use this",
    badJson: "This isn’t valid JSON, even after the usual fixes. Here is where it breaks:",
    invalid: "The JSON is readable but some parts are missing:",
    moreErrors: "…and {n} more",
    err: {
      notObject: "The file isn’t a question paper.",
      noPaper: "There is no “paper” section.",
      noPaperId: "The paper has no “id”.",
      noPaperName: "The paper has no “name”.",
      noQuestions: "There is no “questions” list.",
      qNotObject: "Question {n} is broken.",
      qNoId: "Question {n} has no “id”.",
      qDuplicateId: "Question {n} has the same “id” as an earlier question.",
      qNoText: "Question {n} has no text.",
      qNoOptions: "Question {n} has fewer than 2 options.",
      qNoSubject: "Question {n} has no subject."
    },
    fixed: "Fixed automatically",
    fix: { fences: "code fences", bom: "hidden start mark", smartQuotes: "curly quotes", trailingCommas: "extra commas", backslashes: "stray backslashes" },
    reviewTitle: "Check before adding",
    updateTitle: "This paper is already here",
    updateNote: "Matching questions are updated from the file. Answers, explanations and topics you set in the app are kept when the file has none, and questions not in the file stay.",
    rows: {
      questions: "Questions in the file",
      added: "New questions",
      updated: "Updated questions",
      unchanged: "Unchanged",
      keptAnswers: "Your answers kept",
      keptExplanations: "Your explanations kept",
      keptTopics: "Your topic changes kept",
      notInFile: "In the app but not in the file (kept)",
      deleted: "Deleted by PSC",
      noAnswer: "Without an answer yet",
      newSubjects: "New subjects",
      newTopics: "New topics"
    },
    badAnswers: "{n} questions had an answer number that doesn’t match any option; their answer was left empty.",
    duplicates: "Possibly already in other papers",
    duplicatesHint: "Same wording as a question in another paper. They are still added.",
    addButton: "Add paper",
    updateButton: "Update paper",
    addToBank: "Add to bank",
    added: "Paper added",
    updated: "Paper updated",
    saveFailed: "Saving stopped, so nothing was changed. Error: {error}"
  },
  answerKey: {
    title: "Add answer key",
    hint: "JSON with “answers”: [{ “question_number”, “correct_option”: A–F, or X if deleted by PSC }].",
    wrongFormat: "This isn’t an answer key. It needs an “answers” list.",
    reviewTitle: "Check the answer key",
    otherPaper: "The file says it is for paper {id}, not this one. Check before applying.",
    inFile: "Answers in the file",
    matched: "Matched to questions here",
    willChange: "Will change",
    deleted: "Marked deleted by PSC",
    unmatched: "{n} question numbers aren’t in this paper:",
    unrecognized: "{n} answers couldn’t be read:",
    apply: "Apply {n}",
    done: "{n} questions updated"
  },
  explanations: {
    title: "Add explanations",
    hint: "JSON with “explanations”: [{ “question_number”, “explanation” }].",
    wrongFormat: "This isn’t an explanations file. It needs an “explanations” list.",
    reviewTitle: "Check the explanations"
  },
  banks: {
    yours: "Your banks",
    auto: {
      flagged: "⭐ Flagged",
      flaggedHint: "Questions you flagged",
      wrong: "❌ Still wrong",
      wrongHint: "Your latest answer was wrong or blank"
    },
    newBank: "+ New bank",
    namePlaceholder: "Bank name",
    addTo: "Add to which bank?",
    added: "{n} added to {bank}",
    addFromPool: "+ Add questions",
    importJson: "Import questions (JSON)",
    type: "Type a question",
    rename: "Rename bank",
    delete: "Delete bank",
    deleteTitle: "Delete the bank “{name}”?",
    deleteBody: "Only the bank goes. Its questions stay in their papers.",
    deleted: "Bank deleted",
    missing: "{n} questions in this bank no longer exist."
  },
  pool: {
    title: "Add questions",
    allSubjects: "All subjects",
    allTopics: "All topics",
    allPapers: "All papers",
    search: "Search question text",
    selectShown: "Tick all shown",
    clear: "Clear ticks",
    count: "{n} questions",
    inBank: "already in this bank",
    add: "Add {n}"
  },
  typeQ: {
    markCorrect: "Make {l} the correct answer",
    answerHint: "Tap a letter to mark the correct answer.",
    topic: "Subject and topic",
    pickTopic: "Tap to choose",
    needTopic: "Choose a subject and topic",
    toPool: "Also show it in Library under its topic ({syllabus})",
    saved: "Question saved"
  },
  progress: {
    emptyTitle: "Your progress will show here",
    emptyBody: "After a few tests you’ll see what to study next, where you lose marks, and how you’re improving.",
    soon: ""
  },
  stats: {
    settings: "Progress settings",
    pyq: "PYQ",
    ai: "🤖 AI",
    mode: { pyq: "PYQ questions", ai: "AI questions" },
    period: { all: "All time", "7": "Last 7 days", "30": "Last 30 days", "90": "Last 90 days" },
    periodTitle: "Which tests to count",
    how: "How am I doing",
    per100: "marks per 100 questions",
    vsPrev: "vs previous {n} days",
    what: "What does this mean?",
    per100Info: "Your marks after negative marking (+{pos} right, −{pen} wrong, 0 if left), scaled to a 100-question paper, so a 10-question topic test and a 100-question mock weigh the same.",
    basisInfo: {
      first: "Each question counts once, from your first try: your cold knowledge. Repeating a question can’t inflate or lower it.",
      latest: "Each question counts once, from your most recent try: what you know now.",
      all: "Every answer counts, so questions you repeat count several times."
    },
    accuracy: "of answered right",
    attempted: "attempted",
    questionsCounted: "questions counted",
    trend: "Last {n} tests: {first} → {last} right.",
    trendLabel: "Accuracy in your last {n} tests",
    noAnswersYet: "No answers counted yet here.",
    noTests: "Take a test (▶ Practice on any listing, or Start a test) to see how you’re doing.",
    noAi: "No AI-question tests yet. AI questions arrive in a later update; their results stay separate from your PYQs.",
    stands: "What stands out",
    marksTitle: "Where your marks go",
    mb: { right: "Right: +{n} marks", wrong: "Wrong: {n} questions (−{lost} marks)", blank: "Left: {n} questions" },
    mbNote: "Per 100 questions you earn {right}, lose {lost} to wrong answers, and leave {blank} unanswered.",
    subjects: "Subjects",
    topics: "Topics",
    sort: { weak: "Weakest first", strong: "Strongest first", most: "Most in papers", hard: "Hardest", az: "A–Z" },
    inPapers: (v) => (v.n === 1 ? "1 question in papers" : "{n} questions in papers"),
    answered: "{n} answered",
    fewAnswers: "few answers",
    fewInfo: "Topics with fewer than {n} answers are marked “few answers” and, when ranking, are pulled towards your average so 1 out of 1 doesn’t look like 100%.",
    diffAvg: "difficulty {n}/9",
    notTried: "Not tried",
    allTopics: "All topics",
    tables: "Detailed tables",
    tablesSub: "Time, difficulty, right/wrong by level, guessing",
    openInLibrary: "Open in Library",
    details: "Details",
    avgTime: "Time per question",
    yourAvg: "your average {time}",
    guesses: "Guesses",
    guessSub: "{right} right of {n}",
    levelSub: "{right} right of {n}",
    wrongList: "Questions you got wrong",
    noWrong: "None: your latest answer to every question here was right.",
    pastAnswers: "Your answers in tests",
    basisTitle: "How questions are counted",
    basis: { first: "First try", latest: "Latest try", all: "Every answer" },
    freshTitle: "Start fresh",
    freshInfo: "Your papers, questions, notes, labels, lists, banks and studied counts are never touched.",
    freshKeep: "Start fresh, keep test history",
    freshKeepTitle: "Start fresh from now?",
    freshKeepBody: "Progress counts only tests from now on. Older tests stay in Test history and Still wrong.",
    freshButton: "Start fresh",
    freshDone: "Progress starts fresh from now",
    freshSince: "Counting tests since {date}.",
    unfresh: "Count all tests again",
    unfreshDone: "All tests are counted again",
    freshDelete: "Start fresh and delete all test history…",
    freshDeleteTitle: "Delete all test history?",
    freshDeleteBody: "All {n} finished tests are removed, in every syllabus. Still wrong becomes empty. A safety copy is kept (Settings → Undo).",
    freshDeleteButton: "Delete history",
    freshDeleted: "Test history deleted"
  },
  insight: {
    weakest: "Weakest: {topic} ({sub}): {pct} right in {n} answers.",
    slipping: "Slipping: {topic} went from {from} to {to} in the last 2 weeks.",
    improving: "Improving: {topic} went from {from} to {to} in the last 2 weeks.",
    guessing: "Guessing costs you in {subject}: {net} marks from {n} guesses ({acc} right; it pays only above {be}).",
    slowest: "Slowest: {topic}, {time} per question (your average {avg}).",
    untouched: "Not touched yet: {topic} ({sub}), {n} questions in papers.",
    act: { practise: "Practise", see: "See", why: "Why?", start: "Start" }
  },
  tables: {
    tab: { time: "Time", difficulty: "Difficulty", level: "Right/wrong by level", guess: "Guessing" },
    noData: "No data yet.",
    noTime: "Time per question appears after you take tests in Lakshyam (old scroll-mode times were left out).",
    avgPerQ: "per question",
    timedAnswers: "timed answers",
    timeByDiff: "Time by difficulty",
    timeBySubject: "Time by subject (slowest first)",
    timeByTopic: "Time by topic (slowest first)",
    timeDiffSubject: "Time by difficulty, subject-wise",
    timeDiffTopic: "Time by difficulty, topic-wise",
    diffOff: "Difficulty marking is off. Turn it on in Settings → Display.",
    diffScale: "Easy = 3, Medium = 6, Hard = 9. Averages use only questions with a difficulty, shown as marked/total.",
    avgDiff: "average difficulty",
    marked: "marked",
    qByDiff: "Questions by difficulty",
    accByDiff: "Your accuracy by difficulty",
    takeMarked: "Take tests on questions with a difficulty to see this.",
    diffBySubject: "Average difficulty by subject",
    diffByTopic: "Average difficulty by topic",
    diffByExam: "Average difficulty by exam",
    noAnswers: "No answered questions in this period yet.",
    notMarked: "Not marked",
    all: "All",
    level: "Level",
    right: "Right",
    wrong: "Wrong",
    rightPct: "Right %",
    wrongPct: "Wrong %",
    rwByDiff: "Right vs wrong by difficulty",
    bySubjectRW: "By subject (right/wrong · right %)",
    byTopicRW: "By topic (right/wrong · right %)",
    breakEven: "Marking: +{pos} right, −{pen} wrong. A guess pays off only if you’re right more than {be}% of the time. Rule out even one option and you’re usually above that.",
    noGuesses: "Tap 🤔 Mark as a guess during a test to start collecting this.",
    guessed: "guesses",
    guessAcc: "right",
    netMarks: "net marks",
    guessPays: "👍 Your guesses are paying off.",
    guessCosts: "⚠️ Your guesses are costing marks.",
    gainedLost: "Gained +{gained}, lost −{lost}.",
    by: { subject: "By subject", topic: "By topic" },
    gsort: { "net-asc": "Most lost", "net-desc": "Most gained", count: "Most guesses" },
    guessRow: "{n} guesses · {right}✓ {wrong}✗ · {acc}",
    above: "above break-even",
    below: "below break-even"
  },
  history: {
    title: "Test history",
    none: "No tests yet in this syllabus. Use ▶ Practice on any paper, subject, topic or bank, or Start a test.",
    search: "Search tests",
    group: { all: "All", paper: "Papers", subject: "Subjects", topic: "Topics", bank: "Banks", other: "Mocks & more", ai: "🤖 AI" },
    sort: { recent: "Most recent", az: "A–Z", best: "Best score", worst: "Worst score" },
    groupSub: (v) => (v.n === 1 ? "1 test · {avg}% right · {when}" : "{n} tests · avg {avg}% right · last {when}"),
    testSub: "{right} right · {wrong} wrong · {blank} left"
  },
  practice: {
    button: "Practice",
    testsDone: (v) => (v.n === 1 ? "1 test taken · {last}% right" : "{n} tests taken · last {last}% right")
  },
  start: {
    title: "Start a test",
    whatTitle: "What",
    what: { topic: "This topic", subject: "This subject", paper: "This paper", bank: "A bank", search: "These results", flagged: "Flagged", wrong: "Still wrong", mock: "Mock exam", weak: "Weak areas", review: "These questions" },
    pickBank: "Choose a bank",
    howMany: "How many",
    all: "All {n}",
    pattern: "Exam: {n}",
    skipped: (v) => (v.n === 1 ? "1 question has no correct answer marked, so it’s left out." : "{n} questions have no correct answer marked, so they’re left out."),
    timer: "Timer",
    timerOff: "Off",
    timerOn: "On",
    minutes: "{n} min",
    timerHint: "Suggested {n} min (0.9 min per question). The test submits itself when time runs out. Time stops while paused or when you leave the app.",
    layout: "Layout",
    more: "More options",
    noMore: "Nothing more to set for this one.",
    perSubject: "Questions per subject (total {n})",
    autoSplit: "Split automatically",
    available: "{n} available",
    saveAsBank: "Also save these questions as a bank",
    mixed: "Mix the order",
    mixedHint: "Off keeps the listing’s order.",
    start: (v) => (v.n ? "Start · {n}" : "Start"),
    noneToStart: "No questions to start with.",
    noGradable: "None of these questions has a correct answer marked yet, so a test can’t be scored. Add an answer key or set answers first.",
    hint: {
      mock: "Random questions from every subject, in proportion to how often each subject appears in your papers.",
      weak: "Questions from your {n} weakest topics: topics that appear often and that you get wrong (or haven’t practised).",
      wrong: "Questions where your latest answer was wrong or blank.",
      wrongNone: "Nothing here yet. Questions you get wrong in tests will come here.",
      flagged: "Questions you flagged with ☆.",
      flaggedNone: "No flagged questions yet."
    },
    label: { mock: "Mock exam ({n})", weak: "Weak areas ({n})", wrong: "Still wrong ({n})", flagged: "Flagged ({n})" },
    weakBankName: "Weak areas – {date}",
    bankSaved: "Saved as bank “{name}”",
    unfinishedTitle: "You have an unfinished test",
    continue: "Continue it",
    discardAndNew: "Discard it and start a new one",
    answeredOf: "{n} of {of} answered",
    timeLeft: "{time} left"
  },
  layout: {
    single: "One at a time",
    singleShort: "one at a time",
    singleHint: "Number bar to jump, swipe or Prev / Next",
    scroll: "Scroll",
    scrollHint: "All questions in one long list"
  },
  pager: {
    prev: "Prev",
    next: "Next",
    pos: "{n} of {of}",
    goTo: "Question {n}"
  },
  test: {
    title: "Test",
    none: "No unfinished test.",
    qOf: "{n} / {of}",
    answered: "{n}/{of} answered",
    guess: "Mark as a guess",
    guessOn: "Marked as a guess",
    pause: "Pause",
    paused: "Paused",
    pausedHint: "The timer is stopped and the questions are hidden.",
    resume: "Resume",
    submit: "Submit",
    submitTitle: "Submit the test?",
    submitLeft: (v) => (v.n === 1 ? "1 question is not answered. It counts as left (no marks lost)." : "{n} questions are not answered. They count as left (no marks lost)."),
    timeUp: "Time’s up. The test was submitted.",
    leave: "Save and leave",
    leaveHint: "Continue later from Today. The timer stops while you’re away.",
    discard: "Discard this test",
    discardTitle: "Discard this test?",
    discardBody: "Your answers in this test are thrown away and it won’t count in your history."
  },
  results: {
    short: "{score} / {max}",
    timed: "timed {n} min",
    untimed: "no timer",
    autoSubmitted: "submitted when time ran out",
    breakdown: "{right} right (+{plus}) · {wrong} wrong (−{minus}) · {blank} left",
    marking: "Marking: {right} for a right answer, {wrong} for a wrong one, 0 if left.",
    accuracy: "of answered right",
    attempted: "attempted",
    time: "spent",
    guessLine: "You guessed {n} times and got {right} right. Guessing earned you {net} marks.",
    timingRemoved: "Time per question isn’t shown for this test (the old app recorded it wrongly).",
    missing: (v) => (v.n === 1 ? "1 question from this test no longer exists; its result still counts." : "{n} questions from this test no longer exist; their results still count."),
    ungraded: "{n} questions had no answer marked at the time and weren’t scored.",
    retake: "Retake",
    practiseWrong: "Practise the {n} wrong / left",
    wrongLabel: "Wrong ones: {label}",
    filter: { all: "All", right: "Right", wrong: "Wrong", blank: "Left", "guess-right": "🤔 right", "guess-wrong": "🤔 wrong" },
    sort: { test: "Test order", slow: "Slowest first", fast: "Fastest first", hard: "Hardest first" },
    noneHere: "No questions match this filter.",
    copyWrong: "Copy the wrong / left questions",
    delete: "Delete this test",
    deleteTitle: "Delete this test?",
    deleteBody: "It is removed from your history and from Still wrong. You can undo right after.",
    deleted: "Test deleted"
  },
  review: {
    right: "✓ Right",
    wrong: "✗ Wrong",
    blank: "Not answered",
    ungraded: "Not scored (no answer marked then)",
    guess: "Guess",
    keyChanged: "The correct answer was changed after this test."
  },
  syllabi: {
    title: "Syllabuses",
    add: "+ Add a syllabus",
    namePlaceholder: "e.g. Degree Level Prelims 2026",
    added: "Added {name}",
    editTitle: "Syllabus",
    name: "Name",
    marking: "Marking",
    pos: "Marks for a right answer",
    negNum: "Deduct",
    negDen: "for every … wrong",
    markingWords: "{right} for a right answer, {wrong} for a wrong one.",
    markingShort: "{right} / {wrong}",
    markingNote: "Changes apply to new tests. Past tests keep the marking they were scored with.",
    pattern: "Exam pattern (optional)",
    patternHint: "Fill this in to make mock exams match the real exam. Leave empty to keep the defaults.",
    patternQuestions: "Questions",
    patternMinutes: "Minutes",
    patternShort: "exam: {n} q, {m} min",
    invalid: "Check the name and marking numbers.",
    saved: "Saved",
    delete: "Delete this syllabus",
    cantDelete: "Can’t delete yet",
    cantDeleteBody: "It still has {papers} and {tests}. Move its papers to another syllabus first (paper ⋯ → Move). Tests stay with the syllabus they were taken in.",
    lastOne: "You need at least one syllabus.",
    deleteTitle: "Delete “{name}”?",
    deleteBody: "Its studied counts and labels go too. A safety copy is kept (Settings → Undo).",
    deleted: "Syllabus deleted"
  },
  notes: {
    emptyTitle: "No notes yet",
    emptyBody: "Notes you write on papers, subjects, topics and banks are collected here. Use ⋯ → My note on any of them.",
    myNote: "My note",
    editTitle: "My note",
    placeholder: "Write anything you want to remember here",
    saved: "Note saved",
    removed: "Note removed",
    search: "Search notes",
    open: "Open",
    kind: { question: "Question", topic: "Topic", subject: "Subject", paper: "Paper", bank: "Bank", list: "Topic list", other: "Note" }
  },
  search: {
    title: "Search",
    placeholder: "Search questions, topics, papers",
    hint: "Type at least 2 letters. Searches question text, options and explanations, plus subject, topic and paper names.",
    allSyllabi: "All syllabuses",
    questions: "Questions ({n})",
    viewAll: "View all {n} as a list",
    openTopic: "Open topic",
    openPaper: "Open paper",
    addAllToBank: "Add all to a bank",
    testLabel: "Search: {q}"
  },
  import: {
    reading: "Reading the file…",
    checking: "Checking everything in the file…",
    notJson: "This file isn’t a backup file (it isn’t valid JSON). Pick the .json file you exported.",
    readFailed: "The phone couldn’t read this file. Try picking it again.",
    notBackup: "This file isn’t a PSC Exam Vault or Lakshyam backup. In PSC Exam Vault use Data → Export full backup, then pick that file.",
    reviewTitle: "Check before importing",
    fromFile: "From {file}",
    whatComes: "What will come in",
    rows: {
      syllabuses: "Syllabuses",
      papers: "Question papers",
      questions: "Questions",
      aiQuestions: "AI practice questions (kept separate)",
      deleted: "Questions deleted by PSC",
      noAnswer: "Questions without an answer yet",
      explanations: "Questions with explanations",
      attempts: "Tests in your history",
      studied: "Topics with studied counts",
      labels: "Colour labels",
      lists: "Topic lists",
      banks: "Question banks",
      notes: "Notes",
      flashcards: "Flashcards",
      days: "Study days (streak)"
    },
    labelsPerSyllabus: "{n} after copying to each syllabus that uses the topic",
    namesTitle: "Names tidied up",
    namesBody: "These spellings were the same topic or subject written differently. They are joined under one name; nothing is lost.",
    dupTitle: "Possibly the same (not changed)",
    dupBody: "These look alike but were left as they are. You can merge them later in Library.",
    warnTitle: "Worth knowing",
    skipTitle: "Not imported",
    noneSkipped: "Nothing was skipped.",
    notCarriedTitle: "Not in the backup file",
    notCarried: "AI keys (add them again in Settings when AI arrives), study PDFs, AI style guides, app display settings, and custom topics that have no questions yet.",
    modeTitle: "Lakshyam already has data",
    modeMerge: "Add and update",
    modeMergeHint: "Matching papers, questions and tests are updated. Everything else stays.",
    modeReplace: "Replace everything",
    modeReplaceHint: "Lakshyam’s current data is replaced by this file.",
    safetyNote: "A safety copy of Lakshyam’s current data is kept, so you can undo this from Settings.",
    importButton: "Import",
    restoreButton: "Restore",
    working: "Saving… keep the app open",
    verifiedTitle: "Imported and verified",
    verifiedBody: "Every count was read back from the phone’s storage and matches the file.",
    problemTitle: "Imported, but some counts don’t match",
    problemBody: "The items below differ from the file. Your old app and the file are unchanged. You can undo this import in Settings.",
    failedTitle: "Nothing was changed",
    failedBody: "Saving stopped part-way, so the phone rolled it back. Your data is as it was. Error: {error}",
    backupNow: "Back up Lakshyam now",
    backupHint: "Recommended: keep a Lakshyam backup from day one.",
    checkRow: {
      syllabi: "Syllabuses", subjects: "Subjects", topics: "Topics", papers: "Papers", questions: "Questions",
      flashcards: "Flashcards", questionState: "Flags & difficulty", topicState: "Studied counts",
      attempts: "Tests", sets: "Question banks", topicLists: "Topic lists", labels: "Labels", notes: "Notes",
      filterTemplates: "Saved exam filters", flashcardState: "Flashcard progress", activity: "Study days",
      settings: "Settings", questionsPerPaper: "Papers with a wrong question count", attemptNetTotal: "Total of all test scores"
    },
    warn: {
      "syllabus-created": "A paper pointed to a syllabus that didn’t exist, so it was created.",
      "question-no-id": "Some questions had no ID; one was given based on their position.",
      "question-no-subject": "Some questions had no subject; they are under “Unclassified”.",
      "answer-f-or-deleted": "These questions have 6 options and answer F. The old app may have shown them as deleted; they are kept with answer F. Please check them.",
      "answer-out-of-range": "These questions had an answer that doesn’t match any option; the answer was left empty.",
      "paper-no-questions": "These papers had no questions list.",
      "bank-test-syllabus": "Bank tests were moved to the syllabus most of their questions belong to (they used to show in every syllabus).",
      "timing-removed": "These tests had wrong timing from the old scroll view (all the time on question 1); that timing was left out.",
      "score-computed": "These older tests had no score saved; it was calculated from right/wrong counts with the syllabus marking.",
      "score-mismatch": "The saved score differs from the one calculated now; the saved score was kept.",
      "answer-question-missing": "{n} answers in your test history point to questions that no longer exist. The answers are kept for your stats.",
      "bank-question-missing": "Some bank questions no longer exist and were left out of the bank.",
      "progress-merged": "Studied counts for two spellings of the same topic were added together."
    },
    skip: {
      "paper-no-id": "Papers without an ID",
      "paper-duplicate-id": "Papers with the same ID as an earlier one",
      "question-not-object": "Broken question entries",
      "question-duplicate-id": "Questions repeated inside the same paper",
      "question-no-text": "Questions with no text",
      "question-no-options": "Questions with fewer than 2 options",
      "attempt-no-id": "Tests without an ID",
      "attempt-duplicate-id": "Tests repeated in the file",
      "label-bad": "Labels that couldn’t be read",
      "progress-bad-key": "Studied counts that couldn’t be matched to a topic",
      "flashcard-bad": "Flashcards without text"
    },
    restoreTitle: "Restore this backup?",
    restoreFrom: "Backup made on {date}",
    restoreDamaged: "This file was changed or damaged after it was made. Restoring it may bring back wrong data.",
    restoreNewer: "This backup was made by a newer version of Lakshyam. Update the app first (Settings → Check for update).",
    restoreSkipped: "{n} damaged records will be left out."
  },
  settings: {
    title: "Settings",
    sectionData: "Your data",
    dataSummary: "{papers}, {questions}, {tests} on this phone.",
    importOld: "Import from PSC Exam Vault",
    importOldHint: "Pick the backup file exported from PSC Exam Vault (Data → Export full backup).",
    backupNow: "Back up now",
    lastBackup: "Last backup: {when}",
    neverBackedUp: "No backup made yet",
    restore: "Restore a Lakshyam backup",
    undo: "Undo a recent import or restore",
    undoTitle: "Safety copies",
    undoBody: "Taken automatically before each import, restore, erase, merge, paper update or paper delete. Tap one to put your data back exactly as it was then.",
    undoNone: "No safety copies yet.",
    undoConfirm: "Put data back as it was on {when}?",
    undoConfirmBody: "Lakshyam’s current data will be replaced by this copy. A new safety copy of the current data is kept first.",
    undoButton: "Put it back",
    undoDone: "Data put back as it was on {when}",
    reason: { import: "Before import", restore: "Before restore", undo: "Before undo", erase: "Before erase", merge: "Before merging names", delete: "Before deleting a paper", paper: "Before updating a paper", syllabus: "Before deleting a syllabus", fresh: "Before deleting test history" },
    difficulty: "Difficulty marking",
    difficultyHint: "Shows Easy / Medium / Hard on question cards and lets you sort by it.",
    erase: "Erase Lakshyam’s data",
    eraseTitle: "Erase all study data in Lakshyam?",
    eraseBody: "Papers, questions, tests and notes are removed from Lakshyam only. PSC Exam Vault is not touched. A safety copy is kept, so you can undo this.",
    eraseButton: "Erase",
    erased: "Lakshyam’s data was erased",
    backupSaved: "Backup saved to Downloads",
    sectionToday: "Today",
    goal: "Daily goal (questions answered in tests)",
    goalOther: "Other…",
    goalHint: "Counts questions you answer in tests on this phone’s date.",
    goalInvalid: "Enter a number from 1 to 500.",
    name: "Your name (for the greeting, optional)",
    namePlaceholder: "e.g. Sachin",
    showStreak: "Show the streak and this week",
    showGoal: "Show today’s goal",
    saved: "Saved",
    sectionStorage: "Storage on this phone",
    persistentOn: "Protected from automatic clean-up",
    persistentOff: "Not protected yet. Android may clear app data when the phone is low on space.",
    persistentAsk: "Protect my data",
    persistentGranted: "Data is now protected",
    persistentDenied: "Chrome didn’t allow it yet. It usually allows it after the app is installed and used for a few days.",
    usage: "{used} used of about {quota} available",
    usageUnknown: "Space used isn’t available in this browser",
    sectionDisplay: "Display",
    theme: "Light or dark follows your phone’s setting.",
    sectionApp: "App",
    version: "Version {version}",
    checkUpdate: "Check for update",
    upToDate: "You have the latest version",
    checking: "Checking…",
    offlineNow: "You’re offline. Connect to check for updates.",
    comingTitle: "Coming in later updates",
    coming: "AI keys and AI help, study PDFs and Malayalam names."
  },
  update: {
    ready: "A new version is ready",
    refresh: "Refresh"
  }
};
